apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leblebee
  namespace: leblebee
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.leblebee.com
      secretName: leblebee-www-tls
  rules:
    - host: www.leblebee.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: leblebee
                port:
                  name: http
